# Generated by Django 4.2.7 on 2026-04-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['-created_at'], name='prompts_pro_created_d50e89_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['-complexity'], name='prompts_pro_complex_062460_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['title'], name='prompts_pro_title_fa9f36_idx'),
        ),
    ]
